a = int(input("введите день недели: "))
if a == 1: print("понедельник")
if a == 2: print("вторник")
if a == 3: print("среда")
if a == 4: print("четверг")
if a == 5: print("пятница")
if a == 6: print("суббота")
if a == 7: print("воскресенье")
if a < 1 or a > 7: print("не день недели")